#! /usr/bin/env python3

import os


def print_header():
    print("""
// Package console is generated by generate_resource.py.
package console

var resources = map[string]string{}

func init() {
    """)


def print_footer():
    print("""
}
    """)


def print_file(file_name):
    content = open(os.path.join('resources', file_name)).read()
    print("""

    resources["{}"] = `
{}
`

    """.format(file_name, content))


def main():
    print_header()

    for file_name in os.listdir('resources'):
        print_file(os.path.join(file_name))

    print_footer()


if __name__ == '__main__':
    main()
