#! /usr/bin/env python3

import os
from urllib import request


def print_header():
    print("""
// Package console is generated by generate_resource.py.
package console

var resources = map[string]string{}

func init() {
    """)


def print_footer():
    print("""
}
    """)


def print_file(name, content):
    b = ','.join(str(x) for x in content)
    print("""

    resources["%s"] = string([]byte{%s})

    """ % (name, b))


remote_files = {
}


def main():
    print_header()

    for name in os.listdir('resources'):
        content = open(os.path.join('resources', name), mode='br').read()
        print_file(name, content)

    for name, url in remote_files.items():
        content = request.urlopen(url).read()
        print_file(name, content)

    print_footer()


if __name__ == '__main__':
    main()
